apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: cassandra-storage
  hostPath:
    path: /data/cassandra-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cassandra-storage
  resources:
    requests:
      storage: 5Gi

